name: Capture Teleport Commands

on:
  repository_dispatch:
    types: [webhook_message]

jobs:
  capture_teleport_command:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Capture and log teleport commands
      run: |
        # Aquí filtramos solo los mensajes que contienen "TeleportToPlaceInstance"
        WEBHOOK_MESSAGE=$(curl -s https://discord.com/api/webhooks/1437172422179688575/BOaQBRoUB3ata2etbjg0ycZz1aJt50f6173MnclOiCTJTi3QFcG8Ts1FjYPG_lcIwPyy)
        
        if [[ "$WEBHOOK_MESSAGE" == *"TeleportToPlaceInstance"* ]]; then
          echo "Capturing teleport command..." >> teleport_commands.txt
          echo "$WEBHOOK_MESSAGE" >> teleport_commands.txt
        else
          echo "No teleport command found."
        fi

    - name: Commit captured messages
      run: |
        git config --global user.email "youremail@example.com"
        git config --global user.name "YourName"
        git add teleport_commands.txt
        git commit -m "Update teleport commands"
        git push
